project:
  type: website

website:
  title: "demo-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - nn.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




